# Generated by Django 3.0.3 on 2020-05-05 06:17

from django.db import migrations, models
import django.db.models.deletion
import jiaju.common.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '详情描述',
                'verbose_name_plural': '详情描述',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ordering', models.IntegerField(default=0, verbose_name='排序')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_common.content_set+', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('-ordering', '-create_at'),
            },
        ),
        migrations.CreateModel(
            name='H1',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Content')),
                ('detail', models.CharField(max_length=80, verbose_name='一级标题内容')),
            ],
            options={
                'verbose_name': '一级标题',
                'verbose_name_plural': '一级标题',
            },
            bases=('common.content',),
        ),
        migrations.CreateModel(
            name='H2',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Content')),
                ('detail', models.CharField(max_length=80, verbose_name='二级标题内容')),
            ],
            options={
                'verbose_name': '二级标题',
                'verbose_name_plural': '二级标题',
            },
            bases=('common.content',),
        ),
        migrations.CreateModel(
            name='H3',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Content')),
                ('detail', models.CharField(max_length=80, verbose_name='三级标题内容')),
            ],
            options={
                'verbose_name': '三级标题',
                'verbose_name_plural': '三级标题',
            },
            bases=('common.content',),
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Content')),
                ('detail', models.CharField(max_length=80, verbose_name='小字内容')),
            ],
            options={
                'verbose_name': '小字',
                'verbose_name_plural': '小字',
            },
            bases=('common.content',),
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Content')),
                ('detail', models.TextField(verbose_name='正文内容')),
            ],
            options={
                'verbose_name': '正文',
                'verbose_name_plural': '正文',
            },
            bases=('common.content',),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Content')),
                ('detail', models.ImageField(upload_to=jiaju.common.models.upload_and_rename_internal, verbose_name='图片')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
            bases=('common.content',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='common.Article', verbose_name='详情描述')),
            ],
            options={
                'verbose_name': '段落',
                'verbose_name_plural': '段落',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='common.Section', verbose_name='段落'),
        ),
    ]
