# Generated by Django 3.0.3 on 2020-05-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('ordering', '-create_at'), 'verbose_name': '内容', 'verbose_name_plural': '内容'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('ordering',), 'verbose_name': '段落', 'verbose_name_plural': '段落'},
        ),
        migrations.AddField(
            model_name='section',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
