# Generated by Django 3.0.3 on 2020-05-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200505_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='名称'),
        ),
    ]
