version: '2'

services:
  postgres:
    image: postgres:11.6
  django:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=1234
      - DJANGO_AWS_ACCESS_KEY_ID=1233
      - DJANGO_AWS_SECRET_ACCESS_KEY=1234
      - DJANGO_AWS_STORAGE_BUCKET_NAME=S3-BUCKET
      - DJANGO_AWS_S3_CUSTOM_DOMAIN=s3.s3.amazonaws.com
      - DJANGO_CONFIGURATION=Production
    build: ./backend
    image: caosen-jiaju-backend
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  build_web:
    build: ./frontend
    image: caosen-jiaju-frontend
    command: bash -c "npm i && npm run build:h5"
    volumes:
      - ./frontend:/code
