site_name: jiaju
site_description: A jiaju webapp backend.
repo_url: https://github.com/leishi1313/backend
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/leishi1313">leishi1313</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
