# Generated by Django 3.0.3 on 2020-05-09 22:31

from django.db import migrations, models
import django.db.models.deletion
import jiaju.cases.models
import uuid


class Migration(migrations.Migration):

    replaces = [('cases', '0001_initial'), ('cases', '0002_auto_20200417_0456'), ('cases', '0003_auto_20200429_0231'), ('cases', '0004_auto_20200505_0536'), ('cases', '0005_casedetaileddescription'), ('cases', '0006_auto_20200506_0300'), ('cases', '0007_auto_20200506_0303'), ('cases', '0008_casedetaileddescription'), ('cases', '0009_auto_20200506_0545'), ('cases', '0010_auto_20200506_0547'), ('cases', '0011_auto_20200506_0619'), ('cases', '0012_auto_20200506_0620'), ('cases', '0013_auto_20200506_0623'), ('cases', '0014_auto_20200508_0305'), ('cases', '0015_remove_category_image')]

    initial = True

    dependencies = [
        ('common', '0002_auto_20200505_0646'),
        ('common', '0003_article_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '案例类型',
                'verbose_name_plural': '案例类型',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=80, verbose_name='名称')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.Category')),
            ],
            options={
                'verbose_name': '案例',
                'verbose_name_plural': '案例',
            },
        ),
        migrations.CreateModel(
            name='CasePicture',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('image', models.ImageField(upload_to=jiaju.cases.models.upload_and_rename_case_detail, verbose_name='图片')),
                ('featured', models.BooleanField(default=False, verbose_name='首页展示')),
                ('cover', models.BooleanField(default=False, verbose_name='作为封面')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='cases.Case', verbose_name='案例')),
                ('description', models.CharField(blank=True, max_length=80, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '案例图片',
                'verbose_name_plural': '案例图片',
            },
        ),
        migrations.CreateModel(
            name='CaseDetailedDescription',
            fields=[
                ('article', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Article')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '案例详情描述',
                'verbose_name_plural': '案例详情描述',
            },
        ),
    ]
