# Generated by Django 3.0.3 on 2020-04-17 04:56

from django.db import migrations, models
import django.db.models.deletion
import jiaju.utils


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': '案例', 'verbose_name_plural': '案例'},
        ),
        migrations.AlterModelOptions(
            name='casepicture',
            options={'verbose_name': '案例图片', 'verbose_name_plural': '案例图片'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '类型', 'verbose_name_plural': '类型'},
        ),
        migrations.AddField(
            model_name='casepicture',
            name='description',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='casepicture',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='cases.Case'),
        ),
        migrations.AlterField(
            model_name='casepicture',
            name='image',
            field=models.ImageField(upload_to=jiaju.utils.upload_and_rename, verbose_name='图片'),
        ),
    ]
