# Generated by Django 3.0.3 on 2020-05-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_squashed_0015_remove_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetaileddescription',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
