# Generated by Django 3.0.3 on 2020-04-29 02:31

from django.db import migrations, models
import django.db.models.deletion
import jiaju.utils


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20200417_0456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '案例类型', 'verbose_name_plural': '案例类型'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='123', upload_to=jiaju.utils.upload_and_rename, verbose_name='图片'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casepicture',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='cases.Case', verbose_name='案例'),
        ),
    ]
