# Generated by Django 3.0.3 on 2020-05-05 05:36

from django.db import migrations, models
import jiaju.cases.models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20200429_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casepicture',
            name='image',
            field=models.ImageField(upload_to=jiaju.cases.models.upload_and_rename_case_detail, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=jiaju.cases.models.upload_and_rename_category, verbose_name='图片'),
        ),
    ]
