# Generated by Django 3.0.3 on 2020-05-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20200509_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='short_descriptions',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
    ]
