# Generated by Django 3.0.3 on 2020-05-06 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200505_0646'),
        ('cases', '0004_auto_20200505_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetailedDescription',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Article')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='案例')),
            ],
            options={
                'verbose_name': '案例详情描述',
                'verbose_name_plural': '案例详情描述',
            },
            bases=('common.article',),
        ),
    ]
