# Generated by Django 3.0.3 on 2020-05-06 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200505_0646'),
        ('cases', '0006_auto_20200506_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Article'),
        ),
    ]
