# Generated by Django 3.0.3 on 2020-05-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200505_0646'),
        ('cases', '0007_auto_20200506_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetailedDescription',
            fields=[
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cases.Case', verbose_name='案例')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.Article')),
            ],
            options={
                'verbose_name': '案例详情描述',
                'verbose_name_plural': '案例详情描述',
            },
        ),
    ]
