# Generated by Django 3.0.3 on 2020-05-06 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_casedetaileddescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='article',
        ),
        migrations.RemoveField(
            model_name='casedetaileddescription',
            name='case',
        ),
        migrations.AddField(
            model_name='casedetaileddescription',
            name='case_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cases.Case'),
            preserve_default=False,
        ),
    ]
