# Generated by Django 3.0.3 on 2020-05-06 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20200506_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetaileddescription',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casedetaileddescription',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='cases.Case'),
        ),
    ]
