# Generated by Django 3.0.3 on 2020-05-06 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_auto_20200506_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetaileddescription',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cases.Case'),
        ),
    ]
