# Generated by Django 3.0.3 on 2020-05-06 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_article_name'),
        ('cases', '0012_auto_20200506_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetaileddescription',
            name='article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Article'),
        ),
    ]
