# Generated by Django 3.0.3 on 2020-05-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_auto_20200506_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casepicture',
            name='cover',
            field=models.BooleanField(default=False, verbose_name='作为封面'),
        ),
    ]
