# Generated by Django 3.0.3 on 2020-03-28 05:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='view',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='componentlineitem',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='componentlineitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='component',
            unique_together={('view', 'name')},
        ),
    ]
