# Generated by Django 3.0.3 on 2020-03-29 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0004_auto_20200329_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='component',
            name='view',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='component.View'),
        ),
    ]
