# Generated by Django 3.0.3 on 2020-05-08 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0006_auto_20200329_0553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': '页面元素', 'verbose_name_plural': '页面元素'},
        ),
        migrations.AlterModelOptions(
            name='view',
            options={'verbose_name': '页面', 'verbose_name_plural': '页面'},
        ),
        migrations.AddField(
            model_name='component',
            name='description',
            field=models.CharField(max_length=80, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=80, verbose_name='页面元素名称'),
        ),
        migrations.AlterField(
            model_name='component',
            name='view',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='component.View', verbose_name='页面'),
        ),
    ]
