# Generated by Django 3.0.3 on 2020-05-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200510_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='测试用户', max_length=20),
            preserve_default=False,
        ),
    ]
